### ISSUE TITLE
What happened to club1.fr?

### ISSUE THREAD

**Issue by ShaunYoffe** [club-1/docs#248]
I'm sorry in advance if this is not the correct place to ask, but what happened to club1.fr?
The domain is no longer reachable, and none of the services work as a result.
I see some activity in this repository, so it cant have died.
I am quite confused, as the domain has been down for some time now.
Someone, please explain!

Best Wishes

**Comment by n-peugnet** [comment]
Hello, we have an Internet connection problem since the 5th of June. It should have been restored since the 19th but it is still not yet fixed. [Here is an article](https://github.com/club-1/docs/files/11908691/Rapport.d.incident.003.05_06_2023.-.CLUB1.pdf) (in French) that explains everything about it.

TL;DR: the connection should come back the 3rd of July, but nothing is certain as the dates that our ISP give us feel more and more meaningless.

About the DNS, it was indeed still up since some days ago when I did a mistake with the secondary DNS servers. As all of the services are down anyway I didn't bother to fix it manually, it will be back automatically when the Internet connection comes back.

**Comment by n-peugnet** [comment]
[CLUB1 is now back on the Internet](https://club1.fr/demenagement-cyberrance)
